name: Testapp

on:
  push:
    branches:
      - master

jobs:
  testapplication:
    strategy:
      matrix:
        runner: [ubuntu, spot-runner] # Define labels or environments
    runs-on:
      - self-hosted
      - Linux
      - X64
      - ${{ matrix.runner }} # Use matrix values here

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Docker build and push
      run: |
        docker build -t 3iamlucifer12/testapp -f Dockerfile-multistage .
        docker push 3iamlucifer12/testapp
        
  deploynodeapp:
    needs: [testapplication]
    strategy:
      matrix:
        runner: [ubuntu, spot-runner] # Define labels or environments
    runs-on:
      - self-hosted
      - Linux
      - X64
      - ${{ matrix.runner }} # Use matrix values here

    steps:
    - name: Deploy testapp
      run: |
        docker-compose up -d
        docker ps
