name: Testapp

on:
  push:
    branches:
      - master

jobs:
  testapplication:
    runs-on: [self-hosted, Linux, X64] # Match the labels assigned to your runner
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Docker build and push
      run: |
        docker build -t 3iamlucifer12/testapp -f Dockerfile-multistage .
        docker push 3iamlucifer12/testapp
        
  deploynodeapp:
    runs-on: [self-hosted, Linux, X64] # Match the labels assigned to your runner
    needs: [testapplication]

    steps:
    - name: Deploy testapp
      run: |
        docker-compose up -d
        docker ps
