name: Angular Dashboard

on:
  push:
    branches:
      - sagar

jobs:
  testangularapplication:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run build 
        
  
  deploynodeapp:
    needs: [testangularapplication]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          mkdir -p ~/angular/
          cd ~/angular/
          git clone https://github.com/sagarshrestha24/angular-dashboard.git
          cd angular-dashboard
          
          docker-compose build
          docker-compose up -d 
         
