name: Testapp

on:
  push:
    branches:
      - master

jobs:
  testapplication-ubuntu:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - ubuntu # Label specific to the 'angular-runner-ubuntu'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Docker build and push
      run: |
        docker build -t 3iamlucifer12/testapp -f Dockerfile-multistage .
        docker push 3iamlucifer12/testapp

  testapplication-spot:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - spot-runner # Label specific to the 'spot-runner-ip-10-42-1-231'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Docker build and push
      run: |
        docker build -t 3iamlucifer12/testapp -f Dockerfile-multistage .
        docker push 3iamlucifer12/testapp

  deploynodeapp:
    needs: [testapplication-ubuntu, testapplication-spot]
    runs-on:
      - self-hosted
      - Linux
      - X64
      - ubuntu # Or use a common label if applicable

    steps:
    - name: Deploy testapp
      run: |
        docker-compose up -d
        docker ps
